// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Picnivo.API.Data;

#nullable disable

namespace Picnivo.API.Data.Migrations
{
    [DbContext(typeof(PicnivoDbContext))]
    [Migration("20260702151046_AddEventItemNormalizedLabelUniqueIndex")]
    partial class AddEventItemNormalizedLabelUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Picnivo.API.Data.Models.DateOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("DateOptions");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.DateVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Choice")
                        .HasColumnType("integer");

                    b.Property<Guid>("DateOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DateOptionId");

                    b.HasIndex("ParticipantId", "DateOptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_DateVotes_Participant_DateOption");

                    b.ToTable("DateVotes");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChosenDateOptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ChosenDateOptionId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.EventItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddedByParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedLabel")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("lower(\"Label\")", true);

                    b.Property<Guid?>("OrphanedFromParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddedByParticipantId");

                    b.HasIndex("OrphanedFromParticipantId");

                    b.HasIndex("EventId", "NormalizedLabel")
                        .IsUnique()
                        .HasDatabaseName("IX_EventItems_Event_NormalizedLabel");

                    b.ToTable("EventItems");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.ItemClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EventItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_ItemClaims_EventItem");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ItemClaims");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.Organizer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Organizers");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attendance")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.DateOption", b =>
                {
                    b.HasOne("Picnivo.API.Data.Models.Event", "Event")
                        .WithMany("DateOptions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.DateVote", b =>
                {
                    b.HasOne("Picnivo.API.Data.Models.DateOption", "DateOption")
                        .WithMany()
                        .HasForeignKey("DateOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Picnivo.API.Data.Models.Participant", "Participant")
                        .WithMany("Votes")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DateOption");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.Event", b =>
                {
                    b.HasOne("Picnivo.API.Data.Models.DateOption", "ChosenDateOption")
                        .WithMany()
                        .HasForeignKey("ChosenDateOptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Picnivo.API.Data.Models.Organizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChosenDateOption");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.EventItem", b =>
                {
                    b.HasOne("Picnivo.API.Data.Models.Participant", "AddedByParticipant")
                        .WithMany()
                        .HasForeignKey("AddedByParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Picnivo.API.Data.Models.Event", "Event")
                        .WithMany("Items")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Picnivo.API.Data.Models.Participant", "OrphanedFromParticipant")
                        .WithMany()
                        .HasForeignKey("OrphanedFromParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AddedByParticipant");

                    b.Navigation("Event");

                    b.Navigation("OrphanedFromParticipant");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.ItemClaim", b =>
                {
                    b.HasOne("Picnivo.API.Data.Models.EventItem", "EventItem")
                        .WithOne("Claim")
                        .HasForeignKey("Picnivo.API.Data.Models.ItemClaim", "EventItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Picnivo.API.Data.Models.Participant", "Participant")
                        .WithMany("Claims")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventItem");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.Participant", b =>
                {
                    b.HasOne("Picnivo.API.Data.Models.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.Event", b =>
                {
                    b.Navigation("DateOptions");

                    b.Navigation("Items");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.EventItem", b =>
                {
                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Picnivo.API.Data.Models.Participant", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
